export const SiteName = 'Černoch Martin'
export const SiteUrl = 'https://cernochmartin.com'
export const SiteImage = '/hero-banner.png'
export const SiteLogo = '/profile-picture.png'
export const SiteLanguage = 'en-US'
export const SiteTagLine = 'Web development, Marketing, IT consulting'
export const SiteDescription = 'Hey, I\'m Martin, a full-stack web developer living in Kolín, Czechia. I\'m passionate about building solutions in the Vue, Nuxt and Nest JavaScript frameworks as well as coordination of marketing campaigns and event management.'